prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select (count(distinct ?prop) as ?propCount) where {
	values ?propType {
		rdf:Property
		owl:AnnotationProperty
		owl:AsymmetricProperty
		owl:DatatypeProperty
		owl:DeprecatedProperty
		owl:FunctionalProperty
		owl:InverseFunctionalProperty
		owl:IrreflexiveProperty
		owl:ObjectProperty
		owl:OntologyProperty
		owl:ReflexiveProperty
		owl:SymmetricProperty
		owl:TransitiveProperty
	}
	?prop a ?propType .
}
