ext {
	parliamentVersion = '3.0.0'
	githubOrg = 'raytheonbbn'

	targetDir = file("${rootDir}/target")
	deployableDir = file("${targetDir}/deployableServer")
	depDir = file("${rootDir}/dependencies")
	depDataDir = file("${depDir}/data")
}

allprojects {
	group = 'com.bbn.parliament'
	version = "${parliamentVersion}-SNAPSHOT"

	tasks.withType(JavaCompile).all {
		options.compilerArgs.add('-Xlint:all')
		options.encoding = 'UTF-8'
	}
}

subprojects {
	repositories {
		maven {
			url = uri('https://repo.osgeo.org/repository/release/')
		}
		mavenCentral()
	}
}
