/* CVS $Id: $ */
package com.bbn.parliament.jena.bridge.configuration.vocab;
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from /mnt/c/Users/pwilliam/Projects/parliament/jena/JosekiExtensions/resources/ontology/config-ont.ttl
 * @author Auto-generated by schemagen on 22 Jun 2020 12:18
 */
public class ConfigOnt {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://parliament.semwebcentral.org/parliament-config#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "$Rev$";

    public static final ObjectProperty configurationHandler = m_model.createObjectProperty( "http://parliament.semwebcentral.org/parliament-config#configurationHandler" );

    public static final ObjectProperty index = m_model.createObjectProperty( "http://parliament.semwebcentral.org/parliament-config#index" );

    public static final ObjectProperty indexHandler = m_model.createObjectProperty( "http://parliament.semwebcentral.org/parliament-config#indexHandler" );

    public static final ObjectProperty prefixes = m_model.createObjectProperty( "http://parliament.semwebcentral.org/parliament-config#prefixes" );

    public static final ObjectProperty ruleFile = m_model.createObjectProperty( "http://parliament.semwebcentral.org/parliament-config#ruleFile" );

    public static final DatatypeProperty baselineDir = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#baselineDir" );

    public static final DatatypeProperty clearDataOnStartup = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#clearDataOnStartup" );

    public static final DatatypeProperty deferredFileOutputStreamThreshold = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#deferredFileOutputStreamThreshold" );

    public static final DatatypeProperty enabledByDefault = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#enabledByDefault" );

    public static final DatatypeProperty implementationClass = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#implementationClass" );

    public static final DatatypeProperty prefix = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#prefix" );

    public static final DatatypeProperty processorFactoryClass = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#processorFactoryClass" );

    public static final DatatypeProperty uri = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#uri" );

    public static final DatatypeProperty usageThreshold = m_model.createDatatypeProperty( "http://parliament.semwebcentral.org/parliament-config#usageThreshold" );

    public static final OntClass Configuration = m_model.createClass( "http://parliament.semwebcentral.org/parliament-config#Configuration" );

    public static final OntClass ConfigurationHandler = m_model.createClass( "http://parliament.semwebcentral.org/parliament-config#ConfigurationHandler" );

    public static final OntClass IndexProcessorConfiguration = m_model.createClass( "http://parliament.semwebcentral.org/parliament-config#IndexProcessorConfiguration" );

    public static final OntClass IndexProcessorConfigurationHandler = m_model.createClass( "http://parliament.semwebcentral.org/parliament-config#IndexProcessorConfigurationHandler" );

    public static final OntClass JenaRuleConfigurationHandler = m_model.createClass( "http://parliament.semwebcentral.org/parliament-config#JenaRuleConfigurationHandler" );

    public static final OntClass MemoryConfigurationHandler = m_model.createClass( "http://parliament.semwebcentral.org/parliament-config#MemoryConfigurationHandler" );

    public static final OntClass RuleConfigurationHandler = m_model.createClass( "http://parliament.semwebcentral.org/parliament-config#RuleConfigurationHandler" );

}
