// Copyright (c) 2023 RTX BBN Technologies Corp.

plugins {
	id 'java-library'
}

version = parliamentVersion

dependencies {
	implementation libs.berkeleyDbJe
	implementation libs.jenaArq
	implementation libs.slf4jApi
	implementation project(':Parliament')
	implementation project(':jena:ParliamentClient')
	implementation project(':jena:KbGraph')
	testImplementation libs.logback
	testImplementation(testFixtures(project(":jena:KbGraph")))
}

configurations.all {
	exclude group: 'xml-apis'
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

javadoc {
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath

	options
	{
		//setMemberLevel JavadocMemberLevel.PUBLIC
		//setAuthor true
		addStringOption('Xdoclint:-missing', '-quiet')
	}
}

testing {
	suites {
		test {
			useJUnit()
		}
	}
}

test {
	systemProperty 'java.library.path', "${deployableDir}/bin"
	systemProperty 'test.data.path', "${depDataDir}"
}
