# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
gtVer = "34.4"
jena3Ver = "3.17.0"
# Note: If you change jenaVer, you should probably also change it (in 2 places) in
# OntologyBundle/src/main/java/com/bbn/parliament/ontology_bundle/OntologyBundleExtension.java
jenaVer = "4.10.0"
jupiterVer = "6.1.0"
slf4jVer = "2.0.18"

[libraries]
berkeleyDbJe = "com.sleepycat:je:18.3.12"
commonsCsv = "org.apache.commons:commons-csv:1.14.1"
commonsDbcp = "commons-dbcp:commons-dbcp:1.4"
commonsIo = "commons-io:commons-io:2.22.0"
commonsLang = "org.apache.commons:commons-lang3:3.20.0"
findBugs = "com.google.code.findbugs:annotations:3.0.1u2"
geotoolsEpsgExt = { module = "org.geotools:gt-epsg-extension", version.ref = "gtVer" }		# gt2-
geotoolsEpsgHsql = { module = "org.geotools:gt-epsg-hsql", version.ref = "gtVer" }			# gt2-
geotoolsEpsgWkt = { module = "org.geotools:gt-epsg-wkt", version.ref = "gtVer" }				# gt2-
geotoolsReferencing = { module = "org.geotools:gt-referencing", version.ref = "gtVer" }	# gt2-
geotoolsXsdCore = { module = "org.geotools.xsd:gt-xsd-core", version.ref = "gtVer" }		# gt2-xml-xsd
geotoolsXsdGml = { module = "org.geotools.xsd:gt-xsd-gml3", version.ref = "gtVer" }			# gt2-xml-gml3
geotoolsXsdKml = { module = "org.geotools.xsd:gt-xsd-kml", version.ref = "gtVer" }			# gt2-xml-kml
gson = "com.google.code.gson:gson:2.14.0"
httpClient = "org.apache.httpcomponents:httpclient:4.5.14"
jclOverSlf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4jVer" }
jenaArq = { module = "org.apache.jena:jena-arq", version.ref = "jenaVer" }
jenaCmds = { module = "org.apache.jena:jena-cmds", version.ref = "jenaVer" }
jena3Arq = { module = "org.apache.jena:jena-arq", version.ref = "jena3Ver" }
jts = "org.locationtech.jts:jts-core:1.20.0"
jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiterVer" }
logback = "ch.qos.logback:logback-classic:1.5.32"
postgresql = "org.postgresql:postgresql:42.7.11"
queryBuilder = "com.bbn.parliament:SparqlQueryBuilder:2.0.3"
sesame = "org.openrdf:sesame:1.2.7"
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4jVer" }

[bundles]
#groovy = ["groovy-core", "groovy-json", "groovy-nio"]

[plugins]
springBoot = "org.springframework.boot:4.1.0"
springDepMgmt = "io.spring.dependency-management:1.1.7"
gradlePluginPublish = "com.gradle.plugin-publish:2.1.1"
compatibility = "org.gradle.plugin-compatibility:1.0.0"
#shadow = "com.github.johnrengelman.shadow:8.1.1"
#ontologyBundle = "com.bbn.parliament.OntologyBundle:1.0.8"
