prefix owl:  <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select (count(distinct ?cls) as ?clsCount) where {
	values ?classClass { rdfs:Class owl:Class }
	?cls a ?classClass .
	filter not exists { ?cls a owl:Restriction . }
}
