plugins {
	id 'java-library'
}

repositories {
	mavenCentral()
}

//dependencies {
//	implementation libs.commonsLang
//}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

testing {
	suites {
		test {
			useJUnitJupiter('6.1.0')
		}
	}
}
