# Docker Parliament triple store
#

FROM registry.access.redhat.com/ubi8/ubi:latest
#all the setup under root needed
USER root
ARG https_proxy

RUN yum install -y unzip java-1.8.0-openjdk curl
# Extras for debugging 
# RUN yum install -y procps-ng nmap net-tools

RUN groupadd -g 501 tenant && \
	adduser -r -u 501 -g tenant tenant

WORKDIR /tmp
COPY *.zip Parliament.zip
ARG parl_url
RUN if [ ! -z ${parl_url+x} ]; then rm Parliament.zip; curl -Lk -o Parliament.zip $parl_url; fi  
RUN unzip *.zip
WORKDIR /usr/local/Parliament
RUN dir=`ls -d /tmp/Parliament*/`;cp -r $dir/* .
RUN sed -i 's/localhost/0.0.0.0/' StartParliament.sh \
 && sed -i 's/localhost/0.0.0.0/' conf/jetty.xml
RUN rm -rf /tmp/Parliament*
RUN chown -R tenant:tenant /usr/local/Parliament
#Now only the rest is run as an app user
USER tenant

# Set environment
#
RUN export JAVA_HOME=$(realpath `which java`|sed 's/\/jre\/bin\/java//')
WORKDIR /usr/local/Parliament

EXPOSE 8089
ENTRYPOINT ["./StartParliament.sh"]
