# Docker Parliament triple store
# Note, this requires appropriate credentials and docker login to Ironbank repo to run
#
ARG BASE_REGISTRY=registry1.dso.mil
ARG BASE_IMAGE=ironbank/redhat/openjdk/openjdk8-devel
ARG BASE_TAG=latest

FROM $BASE_REGISTRY/$BASE_IMAGE:$BASE_TAG

USER root
ARG https_proxy

RUN dnf install -y unzip  && \
	dnf clean all && \
	rm -rf /var/cache/dnf


RUN groupadd -g 501 tenant && \
	adduser -r -u 501 -g tenant tenant

WORKDIR /tmp
COPY *.zip Parliament.zip
ARG parl_url
RUN if [ ! -z ${parl_url+x} ]; then rm Parliament.zip; curl -Lk -o Parliament.zip $parl_url; fi
RUN unzip *.zip
WORKDIR /usr/local/Parliament
RUN dir=`ls -d /tmp/Parliament*/`;cp -r $dir/* .
RUN sed -i 's/localhost/0.0.0.0/' StartParliament.sh \
 && sed -i 's/localhost/0.0.0.0/' conf/jetty.xml
RUN rm -rf /tmp/Parliament*
RUN chown -R tenant:tenant /usr/local/Parliament
#Now only the rest is run as an app user
USER tenant

# Set environment
#
RUN export JAVA_HOME=$(realpath `which java`|sed 's/\/jre\/bin\/java//')
WORKDIR /usr/local/Parliament

EXPOSE 8089
ENTRYPOINT ["./StartParliament.sh"]
