#!/bin/bash

version=2.8.1
image_os=ubuntu
#image_os=rhel8
#image_os=win

#docker run -d -it -p 80:8089 --name=parliament-$image_os \
#	--mount type=volume,src=parliament-data-$image_os,dst=/var/parliament-data \
#	parliament-$version-$image_os /bin/bash

docker run -d -p 80:8089 --name=parliament-$image_os \
	--env PARLIAMENT_JAVA_HEAP_SIZE=640m --env PARLIAMENT_BDB_CACHE_SIZE=1g,1 \
	--mount type=volume,src=parliament-data-$image_os,dst=/var/parliament-data \
	parliament-$version-$image_os
