// Copyright (c) 2023 RTX BBN Technologies Corp.

plugins {
	id 'java-library'
	id 'java-test-fixtures'
}

dependencies {
	api libs.jenaArq
	implementation libs.slf4jApi
	implementation project(':Parliament')
	implementation project(':jena:ParliamentClient')
	implementation project(':jena:SparqlQueryBuilder')
	testImplementation libs.logback
	testFixturesImplementation libs.jupiter
	testFixturesImplementation project(':jena:ParliamentClient')
}

configurations.all {
	exclude group: 'xml-apis'
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

javadoc {
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath

	options
	{
		//setMemberLevel JavadocMemberLevel.PUBLIC
		//setAuthor true
		addStringOption('Xdoclint:-missing', '-quiet')
	}
}

testing {
	suites {
		test {
			useJUnitJupiter(libs.versions.jupiterVer)
		}
	}
}

test {
	systemProperty 'java.library.path', rootProject.ext.distDirBin
	systemProperty 'test.data.path', rootProject.ext.depDataDir
}

clean {
	delete "${projectDir}/kb-data"
}
